-- Create Database
CREATE DATABASE IF NOT EXISTS DBT_ELT;

-- Create Schemas
CREATE SCHEMA IF NOT EXISTS DBT_ELT.STAGING;
CREATE SCHEMA IF NOT EXISTS DBT_ELT.ANALYTICS;

-- Create File Format
CREATE OR REPLACE FILE FORMAT my_csv_format
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

-- Create Stage
CREATE OR REPLACE STAGE my_s3_stage
URL='s3://your-bucket-name/'
FILE_FORMAT = my_csv_format;

-- Create Raw Table
CREATE OR REPLACE TABLE DBT_ELT.STAGING.ORDERS (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    ORDER_DATE DATE,
    ORDER_STATUS STRING,
    PRODUCT_ID STRING,
    QUANTITY NUMBER,
    PRICE NUMBER,
    TOTAL_AMOUNT NUMBER,
    CHANGE_TIME TIMESTAMP_NTZ
);
